name: Update data
on:
  schedule:
    - cron: "0 8 * * 1-5" #  At 8:00 on every Monday
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install node packages
        run: npm install
      - name: Run update scripts
        run: |
          python scripts/generate_list.py
          python scripts/convert_to_html.py
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          branch-suffix: "timestamp"
          author: l10n-bot <actions@users.noreply.github.com>
          commit-message: "Update language names"
          title: "Update language names"
