name: Update data
on:
  schedule:
    - cron: '0 8 * * 1-5' #  At 8:00 on every Monday
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install node packages
        run: npm install

      - name: Run update scripts
        run: |
          python scripts/generate_list.py
          python scripts/convert_to_html.py

      - run : git config --global user.email 'flodolo@users.noreply.github.com'
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Update language names"
          branch-suffix: "timestamp"
          title: "Update language names"
